spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: yupao-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: xuyuan-matching
#    password: 12345678
    username: root
    password: 1234
#    url: jdbc:mysql://47.120.70.248:3306/xuyuan-matching?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/xuyuan?serverTimezone=Asia/Shanghai
  # session 失效时间（分钟）
  session:
    timeout: 10m  #
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #解决spring和swagger2版本冲突问题
  redis:
    host: localhost
#    host: 47.120.70.248
    port: 6379
    database: 0
    password:
  #    上线环境时候需要打开
#  profiles:
#    active: prod

#    password: Xuyuan1371480
server:
  port: 8080
  servlet:
    context-path: /api
    #session失效时间
#  address: 0.0.0.0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: 我是许苑向上
    # aaa"
    email: 2517115657@qq.com
    concat: 一心向上
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - xu.yuan.controller
#  smsProperties.getRegionId(),
#  smsProperties.getAccessKey(),
#  smsProperties.getSecretKey()
#  );
#  IAcsClient client = new DefaultAcsClient(profile);
#  SendSmsRequest request = new SendSmsRequest();
#  request.setPhoneNumbers(phoneNum);
#  String signName = smsProperties.getSignName();
#  request.setSignName(smsProperties.getSignName());
#  String templateCode = smsProperties.getTemplateCode();
#  request.setTemplateCode(smsProperties.getTemplateCode());
xuyuan:
  useShort-messagingService: true
  sms:
    region-id: cn-hangzhou
    access-key: LTAI5tH2kzFpCgZFJeLSDpYX
    secret-key: ZbtpjUuLNxJkJLHlBkeMRuechPARFG
    sign-name: 许苑园
    template-code: SMS_468235105
  oos:
    end-point: oss-cn-beijing.aliyuncs.com
    access-key: LTAI5tH2kzFpCgZFJeLSDpYX
    secret-key: ZbtpjUuLNxJkJLHlBkeMRuechPARFG
    bucket-name: xuyuan-up-matching
  ai:
    enable: true
    key: f0df1b534cd25975c82ab741cd9bbc10.vhUDNbxE6mAHrNmh
#  # 阿里云oss
#  aliyun:
#    oss:
#      endpoint: 你自己阿里云账户的endpoint，例如：https://oss-cn-beijing.aliyuncs.com
#      accessKeyId: 你自己阿里云账户的accessKeyId
#      accessKeySecret: 你自己阿里云账户的accessKeySecret
#      bucketName: 你自己阿里云账户的bucketName